---
# - name: Nginx | Modules | Download the ngx_brotli source {{nginx_brotli_url}}
#   get_url:
#     url: "{{nginx_brotli_url}}"
#     dest: /tmp/ngx_brotli_{{nginx_brotli_version}}.tar.gz

# - name: Nginx | Modules | Unpack the ngx_brotli source, version {{nginx_brotli_version}}
#   unarchive:
#     src: /tmp/ngx_brotli_{{nginx_brotli_version}}.tar.gz
#     dest: /tmp
#     remote_src: yes

- name: Nginx | Modules | Git clone Brotli module (google/ngx_brotli)
  ansible.builtin.git:
    repo: https://github.com/google/ngx_brotli.git
    dest: /usr/local/src/ngx_brotli
    recursive: yes
    update: yes
    force: true

- name: Nginx | Modules | Brotli dependencies
  ansible.builtin.apt:
    state: latest
    name:
      - cmake

- name: Create build dir
  ansible.builtin.file:
    path: /usr/local/src/ngx_brotli/deps/brotli/out
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    state: directory

- name: Nginx | Modules | Build brotli dependencies
  ansible.builtin.command:
    chdir: /usr/local/src/ngx_brotli/deps/brotli/out
    cmd: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS="-Ofast -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_CXX_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_INSTALL_PREFIX=./installed ..

- name: Nginx | Modules | Build brotli
  ansible.builtin.command:
    chdir: /usr/local/src/ngx_brotli/deps/brotli/out
    cmd: cmake --build . --config Release --target brotlienc

- name: Nginx | Modules | Copy brotli config
  ansible.builtin.copy:
    src: brotli.conf
    dest: "{{nginx_dir}}/conf.d/brotli.conf"
    mode: '0644'
