# file: nginx/tasks/modules/http_ssl_module.yml
# configure flag: --with-http_ssl_module

- name: get openssl source
  get_url:
    url: "https://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz"
    dest: /tmp/openssl-{{ openssl_version }}.tar.gz
  when: nginx_source_modules_included.openssl is defined

- name: extract openssl source
  unarchive:
    src: /tmp/openssl-{{ openssl_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  when: nginx_source_modules_included.openssl is defined
