---

- name: Nginx | Install the systemd service script
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0644
  register: nginx_service
  notify:
    - restart nginx

- name: Ensure systemd is reloaded if nginx.service has changed
  command: systemctl daemon-reload
  when: nginx_service is changed

